name: Extract Keystore Data

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  export-keystore:
    name: Export Keystore Artifact
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Gerar ficheiro Keystore e resumo
      env:
        KEY_ALIAS: ${{ secrets.REMARKABLE_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.REMARKABLE_KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.REMARKABLE_STORE_PASSWORD }}
        STORE_TYPE: ${{ secrets.REMARKABLE_STORE_TYPE }}
        KEYSTORE_BASE64: ${{ secrets.REMARKABLE_KEYSTORE_BASE64 }}
      run: |
        # Descodifica a Keystore Base64 e cria o ficheiro .jks real
        echo "$KEYSTORE_BASE64" | base64 -d > release.keystore

        # Guarda as senhas num ficheiro de texto
        echo "Alias: $KEY_ALIAS" > credenciais.txt
        echo "Key Password: $KEY_PASSWORD" >> credenciais.txt
        echo "Store Password: $STORE_PASSWORD" >> credenciais.txt
        echo "Store Type: $STORE_TYPE" >> credenciais.txt

    - name: Upload dos ficheiros como Artifact
      uses: actions/upload-artifact@v4
      with:
        name: keystore-recuperada
        path: |
          release.keystore
          credenciais.txt
        retention-days: 1