name: Extract Keystore Data

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  debug:
    name: Extract Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Exportar secrets para ficheiro
      env:
        KEY_ALIAS: ${{ secrets.REMARKABLE_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.REMARKABLE_KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.REMARKABLE_STORE_PASSWORD }}
        STORE_TYPE: ${{ secrets.REMARKABLE_STORE_TYPE }}
        KEYSTORE_BASE64: ${{ secrets.REMARKABLE_KEYSTORE_BASE64 }}
      run: |
        echo "=== INFORMACOES DA KEYSTORE ===" > keystore_info.txt
        echo "Alias: $KEY_ALIAS" >> keystore_info.txt
        echo "Key Password: $KEY_PASSWORD" >> keystore_info.txt
        echo "Store Password: $STORE_PASSWORD" >> keystore_info.txt
        echo "Store Type: $STORE_TYPE" >> keystore_info.txt
        echo "" >> keystore_info.txt
        echo "=== BASE64 DA KEYSTORE ===" >> keystore_info.txt
        echo "$KEYSTORE_BASE64" >> keystore_info.txt

    - name: Iniciar sessão SSH (tmate)
      uses: mxschmitt/action-tmate@v3